# Generated by Django 3.1 on 2020-09-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_good_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='supplier',
            field=models.CharField(blank=True, max_length=256, verbose_name='имя поставщика'),
        ),
    ]
